add left menu
mishanika/mishagram pull request #2
Opened 2022-11-19 18:21 UTC by mishanika

2022-12-04 11:32 UTC, mishanika reviewed
Сделал папку assets, добавил туда компоненты свгшек и папку png картинок. Поспешил и создал файлы главной части страницы

2022-12-07 14:31 UTC, mishanika reviewed
Вынес текст в отдельный файл с константами, добавил для SVG компонентов аргументы, с помощью которых при клике будет менять сама SVG в меню, немного изменил функцию для смены.

2022-12-09 19:50 UTC, mishanika reviewed
Добавил интерфейсы для пропсов у свг и сделал обводку для профиля при клике

2022-12-09 19:55 UTC, Io38 requested changes

2022-12-09 21:06 UTC, Io38 approved these changes

2022-12-09 21:29 UTC, merged