add login menu
mishanika/mishagram pull request #6
Opened 2023-01-11 12:54 UTC by mishanika

2023-01-20 18:59 UTC, Io38 requested changes

2023-01-20 18:59 UTC, Io38 commented on src/containers/login/Login.tsx
> +  };
отступ

2023-01-20 18:59 UTC, Io38 commented on src/containers/login/Login.tsx
> +  };
отступ

2023-01-20 18:59 UTC, Io38 commented on src/containers/login/Login.tsx
> +    setInterval(() => {
always clear intervals and event listenters

2023-01-20 18:59 UTC, Io38 commented on src/containers/navigation/routes.tsx
> +//import Registration from '../login/Login';
delete comment

2023-01-21 16:30 UTC, mishanika reviewed
![image](https://user-images.githubusercontent.com/118487692/213876754-639eac3b-6d72-4441-9492-eafaf70947f6.png)
![image](https://user-images.githubusercontent.com/118487692/213876767-53e4e009-51c8-4172-958b-248cb3405434.png)
![image](https://user-images.githubusercontent.com/118487692/213876777-f990cb3e-7c9e-4e7f-8c3c-1cffcfbd8f83.png)

2023-01-23 17:46 UTC, merged